input.onSound(DetectedSound.Loud, function () {
    music.play(music.tonePlayable(698, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
    basic.showIcon(IconNames.Yes)
    basic.showString("ON")
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.clearScreen()
})
input.onLogoEvent(TouchButtonEvent.Touched, function () {
    basic.showNumber(input.lightLevel())
})
input.onButtonPressed(Button.A, function () {
    music.play(music.tonePlayable(698, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
    basic.showIcon(IconNames.Yes)
    basic.showString("ON")
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    music.play(music.tonePlayable(147, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
    basic.showIcon(IconNames.No)
    basic.showString("OFF")
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.clearScreen()
})
basic.showString("Self Test")
music.play(music.tonePlayable(698, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
basic.pause(1000)
music.play(music.tonePlayable(147, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
basic.pause(1000)
pins.digitalWritePin(DigitalPin.P2, 1)
basic.pause(1000)
pins.digitalWritePin(DigitalPin.P2, 0)
basic.pause(1000)
basic.showString("Ready")
